baseURL = "https://raciod.github.io/"
languageCode = "en-us"
title = "Raciod"
theme = "PaperMod"

[params]
  defaultTheme = "dark"
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  disableThemeToggle = false
